---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rnote

<!-- badges: start -->
<!-- badges: end -->

rnote is a simple package that allows you to make notes and recall them from any project by saving them to the package directory.

## Installation

You can install the development version of rnote from [GitHub](https://github.com/filmicaesthetic/rnote) with:

``` r
# install.packages("devtools")
devtools::install_github("filmicaesthetic/rnote")
```

## Example

### Make a note:
```{r}
rnote::jotdown(note = "this is a note", topics = c("test_topic1", "test_topic2"))
```

### Recall notes to console:
```{r}
rnote::checknotes(topic = "test_topic1", current_project = TRUE, n = 10)
```

### Back up notes to new location:
```{r eval = FALSE}
rnote::backup.notes(file = "notes.csv", current_project = FALSE)
```

## Demo video

<blockquote class="twitter-tweet"><p lang="en" dir="ltr"><a href="https://t.co/uoEuCTIioX">pic.twitter.com/uoEuCTIioX</a></p>&mdash; Dan (@FilmicAesthetic) <a href="https://twitter.com/FilmicAesthetic/status/1558535899352375302?ref_src=twsrc%5Etfw">August 13, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
